#!/bin/bash

# getip - collecting ip from local machine to file
# version 2.0

mkdir -p tmp
cd tmp
echo creating the "file..."
curl ipecho.net |grep "Your IP" | awk '{print $4}' | awk -F "<" '{print $1}' > text.dat
echo $(date) >> text.dat