#!/bin/bash

# getip - collecting ip from local machine to file
# version 2.0

mkdir -p tmp
cd tmp
echo creating the "file..."
ifconfig | grep "inet[^6]" | awk '{print $2}' | head -n1 > text.dat
echo $(date) >> text.dat